import Head from "next/head";
import { FC, useState } from "react";
import TodoForm from "../components/Todo/TodoForm";
import TodoList from "../components/Todo/TodoList";
import { ITodo, ITodoList } from "../types";
import Header from "../components/Header";

const Home: FC<ITodoList> = ({ todos }) => {
  const [allTodos, setAllTodos] = useState<ITodo[]>(todos);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Header />
        <TodoForm todos={allTodos} setTodos={setAllTodos} />
        <TodoList todos={allTodos} setTodos={setAllTodos} />
      </main>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const res = await fetch(`http://localhost:3000/api/getAllTodos`);
  const todos = await res.json();

  return {
    props: { todos }, // will be passed to the page component as props
  };
}
